# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ij0GXUUA8CCTrfnHsdAnncHlH0LtGoYd
"""

# !pip install numpy matplotlib pandas scipy

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.interpolate import interp1d
from scipy.ndimage import gaussian_filter1d
from scipy.integrate import simps
from scipy.integrate import simps

from scipy import integrate

from scipy.integrate import simpson

def denoise_and_norm(data: np.ndarray, wavelength: np.ndarray, denoising: bool, normalising: bool, sigma_nm: float = 7.,
                     normalised_at_wvl: float = 550.) -> np.ndarray:
    if np.ndim(data) == 1:
        data = np.reshape(data, (1, len(data)))

    if denoising:
        nm_to_px = 1. / (wavelength[1] - wavelength[0])  # conversion from nm to px
        correction = gaussian_filter1d(np.ones(len(wavelength)), sigma=sigma_nm * nm_to_px, mode="constant")
        data_denoised = gaussian_filter1d(data, sigma=sigma_nm * nm_to_px, mode="constant") / correction
    else:
        data_denoised = data

    # Normalised reflectance
    if normalising:
        fun = interp1d(wavelength, data_denoised, kind="cubic")  # v_final differs from v
        v_norm = np.reshape(fun(normalised_at_wvl), (len(data_denoised), 1))
    else:
        v_norm = 1.

    #return data_denoised / v_norm
    return (data_denoised / v_norm).flatten()

data = pd.read_excel("A2.xlsx",
                   header=0)

print(data.head())

data.head()

wavelengths_new = np.arange(550., 2500, 20.)

wavelengths, spectra = data["W"].to_numpy(), data["R"].to_numpy()

# Interpolate the spectra onto the new wavelengths using cubic interpolation (by ignoring the duplicate values)
unique_wavelengths, unique_indices = np.unique(wavelengths, return_index=True)
unique_spectra = spectra[unique_indices]

interp_func = interp1d(unique_wavelengths, unique_spectra, kind="linear")
interpolated_spectra = interp_func(wavelengths_new)

# Call the denoise function
denoised_normalized_data = denoise_and_norm(interpolated_spectra, wavelengths_new, denoising=True, normalising=False)

# input_data[i,] = denoised_normalized_data

plt.plot(wavelengths_new/1000, denoised_normalized_data)

plt.xlabel("Wavelength (µm)", fontsize=12)
plt.ylabel("Reflectance", fontsize=12)
plt.tick_params(axis='x', labelsize=10)
plt.tick_params(axis='y', labelsize=10)
savefig_kwargs = {"bbox_inches": "tight",
                  "pad_inches": 0.05,
                  "dpi": 100}  # dpi only for jpg/png figures
plt.savefig('Samples.png', format='png', **savefig_kwargs)

# Define wavelength and reflectance data
x = wavelengths_new  # wavelength data
y = denoised_normalized_data # reflectance data

#ploting the spectral slop along the maximum points between 500-100 nm, 1400-1500 nm and the last point
#you can change these points according to your spectral data

# Find maximum points in specified ranges
mask1 = (x >= 500) & (x <= 1000)
mask2 = (x >= 1400) & (x <= 1500)

x1 = x[mask1][np.argmax(y[mask1])]
y1 = y[mask1][np.argmax(y[mask1])]

x2 = x[mask2][np.argmax(y[mask2])]
y2 = y[mask2][np.argmax(y[mask2])]

x3 = x[-1] #last point of the wavelength data
y3 = y[-1] #last point of the reflectance data

# Plot the reflectance data
plt.figure(figsize=(10, 6))
plt.plot(x, y, label='Reflectance', color='blue')

# Plot the spectral slope line connecting the three points
plt.plot([x1, x2, x3], [y1, y2, y3], color='red', linewidth=2, label='Spectral Slope')
plt.scatter([x1, x2, x3], [y1, y2, y3], color='black', zorder=5)

plt.title('Reflectance vs. Wavelength with Updated Spectral Slope Line')
plt.xlabel('Wavelength (nm)')
plt.ylabel('Reflectance')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Slope removal using three key points

fit_x = np.array([x1, x2, x3])
fit_y = np.array([y1, y2, y3])
coeffs = np.polyfit(fit_x, fit_y, 1)
trend = np.polyval(coeffs, x)
y_flat = y - trend + np.mean(fit_y)

baseline = np.mean(fit_y)

#calculating band depth and HBW
# Segment 1: x1 to x2
seg1_mask = (x >= x1) & (x <= x2)
x_seg1 = x[seg1_mask]
y_seg1 = y_flat[seg1_mask]
depth1 = baseline - np.min(y_seg1)
half_depth1 = baseline - depth1 / 2
left_idx1 = np.where(y_seg1 <= half_depth1)[0][0]
right_idx1 = np.where(y_seg1 <= half_depth1)[0][-1]
hbw1 = x_seg1[right_idx1] - x_seg1[left_idx1]

# Segment 2: x2 to x3
seg2_mask = (x >= x2) & (x <= x3)
x_seg2 = x[seg2_mask]
y_seg2 = y_flat[seg2_mask]
depth2 = baseline - np.min(y_seg2)
half_depth2 = baseline - depth2 / 2
left_idx2 = np.where(y_seg2 <= half_depth2)[0][0]
right_idx2 = np.where(y_seg2 <= half_depth2)[0][-1]
hbw2 = x_seg2[right_idx2] - x_seg2[left_idx2]

# Plot
plt.figure(figsize=(10, 6))
plt.plot(x, y_flat, label='Flattened Reflectance', color='gray')
plt.axhline(baseline, color='red', linestyle='--', label='Baseline')
plt.fill_between(x_seg1, y_seg1, baseline, color='blue', alpha=0.3, label='Band 1')
plt.fill_between(x_seg2, y_seg2, baseline, color='green', alpha=0.3, label='Band 2')
plt.vlines([x_seg1[left_idx1], x_seg1[right_idx1]], ymin=np.min(y_seg1), ymax=baseline, color='blue', linestyle='--')
plt.vlines([x_seg2[left_idx2], x_seg2[right_idx2]], ymin=np.min(y_seg2), ymax=baseline, color='green', linestyle='--')
plt.text((x_seg1[left_idx1]+x_seg1[right_idx1])/2, np.min(y_seg1),
         f"Depth: {depth1:.3f}\nHBW: {hbw1:.1f} nm", ha='center', va='top',
         fontsize=8, bbox=dict(facecolor='white', alpha=0.6))
plt.text((x_seg2[left_idx2]+x_seg2[right_idx2])/2, np.min(y_seg2),
         f"Depth: {depth2:.3f}\nHBW: {hbw2:.1f} nm", ha='center', va='top',
         fontsize=8, bbox=dict(facecolor='white', alpha=0.6))

plt.title('Absorption Band Depth and Half-Bandwidth')
plt.xlabel('Wavelength (nm)')
plt.ylabel('Reflectance')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

#calculate the area of the absorption bands

# Segment 1: Area between x1 and x2
area1 = simpson(baseline - y_seg1, x_seg1)

# Segment 2: Area between x2 and x3
area2 = simpson(baseline - y_seg2, x_seg2)

print(f"Area under Band 1: {area1:.3f}")
print(f"Area under Band 2: {area2:.3f}")

